version: '2'
services:
  asterisk15:
    build: .
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./store/etc/asterisk/:/etc/asterisk/"
      - "./store/var/log/asterisk:/var/log/asterisk"
      - "./store/var/menu:/var/menu/"       
    restart: always